# Generated by Django 4.2.7 on 2023-11-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='end_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='start_Date',
            field=models.DateField(),
        ),
    ]
